### ISSUE TITLE
[hammerhead] Display on mainline

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/linux#2]
The display on hammerhead turns on with weston and draws only a single frame which doesn't completely fill the display. I also can't get it to draw a new frame by restarting weston.

![img_20180419_225407](https://user-images.githubusercontent.com/6928199/39017896-ce07d4a8-4424-11e8-9db3-6c1c00f52fe5.jpg)

```
[  373.327879] msm fd900000.mdss: pp done time out, lm=0
[  373.607892] msm fd900000.mdss: pp done time out, lm=0
[  373.667895] msm fd900000.mdss: pp done time out, lm=0
[  373.727889] msm fd900000.mdss: pp done time out, lm=0
[  373.787904] msm fd900000.mdss: pp done time out, lm=0
[  373.877900] msm fd900000.mdss: pp done time out, lm=0
[  373.937880] msm fd900000.mdss: pp done time out, lm=0
[  373.997895] msm fd900000.mdss: pp done time out, lm=0
[  374.057895] msm fd900000.mdss: pp done time out, lm=0
[  374.117899] msm fd900000.mdss: pp done time out, lm=0
[  374.177888] msm fd900000.mdss: pp done time out, lm=0
[  403.708044] detected fb_set_par error, error code: -16
[  403.847914] msm fd900000.mdss: pp done time out, lm=0
[  403.927890] msm fd900000.mdss: pp done time out, lm=0
[  405.687917] msm fd900000.mdss: pp done time out, lm=0
[  405.747908] msm fd900000.mdss: pp done time out, lm=0
[  405.807885] msm fd900000.mdss: pp done time out, lm=0
```

After unplugging the USB lead it drew a single frame again. This time a full frame.

It also seems like only half of the backlight leds are turned on since the screen has a dark corner on the bottom right.

![img_20180419_225744](https://user-images.githubusercontent.com/6928199/39018097-5734b4ee-4425-11e8-96b8-2cbc8a4968b0.jpg)

Looks like that on some bootups it runs incredibly smooth for a minute and then it crashes and the screen gets garbled. Also one weird thing is that the ball in weston-simple-damage doesn't move while the screen does refresh.

**Comment by bhush9** [comment]
This is possibly packaging or weston issue, or even local setup issue, but not a kernel issue itself. I am closing this and re-opening issue on pmbootstrap.

**Comment by MartijnBraam** [comment]
Even the half working backlights?

**Comment by ollieparanoid** [comment]
Closing, let's keep the discussion in the other issue.
